version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mjml
    versions:
    - 4.8.1
    - 4.8.2
    - 4.9.0
  - dependency-name: js-yaml
    versions:
    - 4.0.0
